#!/bin/bash

# Setup ROS distro and ROS
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
apt-get update
apt-get install -y ros-$ROS_DISTRO-ros-base ros-dev-tools 

# Install some misc packages
apt-get install -y cpufrequtils libraspberrypi-bin rt-tests cpuset stress stress-ng build-essential

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
